<?php

use \Drupal\Core\Template\Attribute;

/**
 * Prepares variables for layout templates.
 *
 * @param array &$variables
 *   An associative array containing:
 *   - content: An associative array containing the properties of the element.
 *     Properties used: #settings, #layout.
 */
function calibr8_layouts_preprocess_layout(&$variables) {
  // get region list
  $layout = $variables['content']['#layout'];
  if($layout) {
    $regions = $layout->getRegions();
    // Check for empty regions and provide info to template
    if($regions) {
      foreach($regions as $region => $region_name) {
        $region_empty = true;
        if (isset($variables['content'][$region])) {
          foreach($variables['content'][$region] as $key => $child) {
            if ($key === '' || $key[0] !== '#') {
              $region_empty = false;
              break;
            }
          }
        }
        $variables[$region . '_empty'] = $region_empty;
      }
    }
  }
  // add attributes
  $variables['layout_classes'] = new Attribute();
}
